# Generated by Django 6.0 on 2025-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recovery_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='恢复密钥'),
        ),
    ]
