# Generated by Django 6.0 on 2025-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_recovery_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recovery_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='恢复密钥'),
        ),
    ]
