# Generated by Django 6.0 on 2025-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
