# Generated by Django 6.0 on 2025-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recovery_key',
            field=models.CharField(default='OLD_DATA', max_length=128, verbose_name='加密恢复密钥'),
            preserve_default=False,
        ),
    ]
